// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdxymkwxqlybezzriocf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeHlta3d4cWx5YmV6enJpb2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNTM1NjUsImV4cCI6MjA3NzgyOTU2NX0.t1n3a9NmyIFEW0ThN-tZx1udyDJITFN-pWjXYNJlVJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});